######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 18 14:24:54 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . image
INCLUDEPATH += .

# Input
HEADERS += widget.h \
    lyric.h
FORMS += widget.ui \
    lyric.ui
SOURCES += main.cpp widget.cpp \
    lyric.cpp
RESOURCES += image/res.qrc
